### ISSUE TITLE
Strip OKTA-* and Token headers

### ISSUE THREAD

**Issue by lucmir** [techops-staffing/kong-okta-auth-plugin#6]
All OKTA-* headers should be stripped before including the headers from token data. This procedure avoids that headers from the original request reaches the API and are trusted as being the headers that hold auth data.

The  "token" header should be also stripped as they are no longer required by APIs.

**Comment by pduldig-at-tw** [comment]
This is really important to remove the header injection vulnerability from Kong.
As a mitigation against edge cases, we should sign these headers -- 

for example (and these are not real vulns, they are to provide some intuition on the risks at play), 

lets say an attacker knows that a unicode Swedish 'O' character is collated to ASCII 'O' by an application; In order to prevent a unicode-confusion injection, have the application verify the header originated from Kong.

Attacker knows that nginx will split a specially encoded request in request into 2 seperate requests to the back end; Attacker injects the admin header into the 2nd request, which bypasses the Kong check.

**Comment by pduldig-at-tw** [comment]
Token should be removed as to discourage applications from attempting to validate or use the token.
